##CONFIG FILE
##NO MORE CREEPERS VERSION 1.0.2
##FOR VERSION 1.19.4
##CREATED BY ASTERIA LIGHT GAMES

SPAWN-PREVENTION:
#Any mob in this section can be disabled by changing spawn to false
#Creepers are false by default
  CREEPER:
    SPAWN: false
  ZOMBIE:
    SPAWN: true
  SKELETON:
    SPAWN: true
  SPIDER:
    SPAWN: true
  ENDERMAN:
    SPAWN: true

ADDITIONAL-FEATURES:
  ##Can creepers explode?(true by default)
  CREEPERS-EXPLODE: true

  ##Can zombie's call for reinforcements? (true by default)
  ZOMBIE-REINFORCEMENTS: true

  ##Should skeletons spawn with bows (true by default)
  SKELETON-BOWS: true

  ##Can endermen teleport
  ENDERMAN-TELEPORT: true



FUN:
  #Just for fun

#Replace 1/1000 zombies with a giant?
  SPAWN-GIANTS: false

#Should all vindicators be johnny?
  HERES-JOHNNY: false

#Should all sheep be rainbows?
  RAINBOW-SHEEP: false

#should creepers explode on death
  MARTYRDOM: false

